# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KagiCli < Formula
  desc "Kagi CLI — secrets management for Sensey"
  homepage "https://github.com/senseylabs/kagi-cli"
  version "0.14.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.14.1/kagi-cli_0.14.1_darwin_amd64.tar.gz"
      sha256 "11844c6900cafa332908800516f8ea1cbca3042226715d1fbf7722b01dedf782"

      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.14.1/kagi-cli_0.14.1_darwin_arm64.tar.gz"
      sha256 "082b03594b1338ef62d0a4e6523e64d0ea829865c85dc9689d3690b71b47b921"

      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.14.1/kagi-cli_0.14.1_linux_amd64.tar.gz"
      sha256 "d1a08d5da221a183bac5150d296c93850ae5a831708204a6c15a7a0c21222f4a"
      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  test do
    system "#{bin}/kagi", "--version"
  end
end
