# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KagiCli < Formula
  desc "Kagi CLI — secrets management for Sensey"
  homepage "https://github.com/senseylabs/kagi-cli"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.8.0/kagi-cli_0.8.0_darwin_amd64.tar.gz"
      sha256 "d2d381804b8219f4d1abbf12143f5ab63a61ae33f88be4acdaab6e764dae7062"

      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.8.0/kagi-cli_0.8.0_darwin_arm64.tar.gz"
      sha256 "522c7260f058cbc8e970e242abc2453d9bcb5764e78bcc7cb4f23f4cae2c1803"

      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.8.0/kagi-cli_0.8.0_linux_amd64.tar.gz"
      sha256 "7179995aac366ef333389410bf99698e98dfb30d5b7a4dcb7edf39b67261b576"
      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  test do
    system "#{bin}/kagi", "--version"
  end
end
