# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kagi < Formula
  desc "Kagi CLI — secrets management for Sensey"
  homepage "https://github.com/senseylabs/kagi-cli"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.18.0/kagi-cli_0.18.0_darwin_amd64.tar.gz"
      sha256 "e88e5556126f59d6e8447e06f7bdb2731cf06f4956c300ae42c677797532900a"

      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.18.0/kagi-cli_0.18.0_darwin_arm64.tar.gz"
      sha256 "3a6c96e9059b788ebffed815194735d0b823bb17872f64b2bc40e64760ad6c0f"

      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.18.0/kagi-cli_0.18.0_linux_amd64.tar.gz"
      sha256 "759f50f3c44389884ff2c27c5f4107b8915ff15df0fa6c0b691501b6b631fb0c"
      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.18.0/kagi-cli_0.18.0_linux_arm64.tar.gz"
      sha256 "46fb6a57d1f2cc57034109e0460148d4b1bbcdb1b90d87f1727f455f82421bba"
      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  test do
    system "#{bin}/kagi", "--version"
  end
end
