# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KagiCli < Formula
  desc "Kagi CLI — secrets management for Sensey"
  homepage "https://github.com/senseylabs/kagi-cli"
  version "0.27.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.27.0/kagi-cli_0.27.0_darwin_amd64.tar.gz"
      sha256 "b7174cb54d3700a91c3f2e9a018a3ce21aacdccdd5877b29ebcfd3260337bd67"

      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.27.0/kagi-cli_0.27.0_darwin_arm64.tar.gz"
      sha256 "10efcbd10b09cfa83a700e8cb2fa840e800ebf3b199a4e8f7e26e6bfb697f718"

      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.27.0/kagi-cli_0.27.0_linux_amd64.tar.gz"
      sha256 "abaddc0085f30d634928afa881dbdb8f5378468110775bd2216c288625154d26"
      define_method(:install) do
        bin.install "kagi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kagi-cli/releases/download/v0.27.0/kagi-cli_0.27.0_linux_arm64.tar.gz"
      sha256 "c70463b8e00a5c2b8b4639d072931fa5c8a2db21f4847158266a35603483d2b8"
      define_method(:install) do
        bin.install "kagi"
      end
    end
  end

  test do
    system "#{bin}/kagi", "--version"
  end
end
