# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaizenCli < Formula
  desc "CLI tool for Kaizen board management"
  homepage "https://github.com/senseylabs/kaizen-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.2.0/kaizen-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "2ba21a2f7248f9d9648818c3e2e4ed1a98dbf02cdc2d9cd2e165bf5f72b7804b"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.2.0/kaizen-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "08df39f3770949baba97d94f23b7573d7b809759919fbf3f6a9097178974869b"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.2.0/kaizen-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "c6194b0aa8d7a24cdea5def7a62a2eaa8fa9326af94868b40eef500b582b4d1f"
      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  test do
    system "#{bin}/kaizen", "--version"
  end
end
