# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaizenCli < Formula
  desc "CLI tool for Kaizen board management"
  homepage "https://github.com/senseylabs/kaizen-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.1/kaizen-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "7355ee47580742de4690afcd213fbdc5ba4bac5b57c8b8b0a2955298d2a50129"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.1/kaizen-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "a75c776788ed10d081dcdfbfe4e0d8305e6636d124d66173c466bf4c56ea1c95"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.1/kaizen-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "dbe57d83c2685ecfffa0935e56bf15bacef739fe17149617a14d14b677b1285a"
      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  test do
    system "#{bin}/kaizen", "--version"
  end
end
