# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaizenCli < Formula
  desc "CLI tool for Kaizen board management"
  homepage "https://github.com/senseylabs/kaizen-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.0/kaizen-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "c1f128eea0c31e02fcc9711f6628baa1239d6e7a8e6c69f923282fd385eb5ec0"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.0/kaizen-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "1d018828ca2ee1fca097fbf7ce12a4268139a4ffd553e4aa92f9827518dbf5f0"

      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/senseylabs/kaizen-cli/releases/download/v0.4.0/kaizen-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "8add2a4595c74d271533ae5956066fbe2418d83377a2515cc6a683e682f2f216"
      define_method(:install) do
        bin.install "kaizen"
      end
    end
  end

  test do
    system "#{bin}/kaizen", "--version"
  end
end
